<?php

declare(strict_types=1);

namespace Wise\Core\Security\Constants;

class ScopeNames
{
    public const GENERAL_ACCESS = 'GENERAL_ACCESS';
    public const GENERAL_PUT = 'GENERAL_PUT';
    public const GENERAL_PATCH = 'GENERAL_PATCH';
    public const GENERAL_GET = 'GENERAL_GET';
    public const GENERAL_DELETE = 'GENERAL_DELETE';

    public const AGREEMENTS_ALL = 'AGREEMENTS_ALL';
    public const AGREEMENTS_PUT = 'AGREEMENTS_PUT';
    public const AGREEMENTS_PATCH = 'AGREEMENTS_PATCH';
    public const AGREEMENTS_GET = 'AGREEMENTS_GET';
    public const AGREEMENTS_DELETE = 'AGREEMENTS_DELETE';
    public const AGREEMENTS_TYPES_PUT = 'AGREEMENTS_TYPES_PUT';

    public const USER_AGREEMENTS_ALL = 'USER_AGREEMENTS_ALL';
    public const USER_AGREEMENTS_PUT = 'USER_AGREEMENTS_PUT';
    public const USER_AGREEMENTS_PATCH = 'USER_AGREEMENTS_PATCH';
    public const USER_AGREEMENTS_GET = 'USER_AGREEMENTS_GET';
    public const USER_AGREEMENTS_DELETE = 'USER_AGREEMENTS_DELETE';
    public const USER_AGREEMENTS_TYPES_PUT = 'USER_AGREEMENTS_TYPES_PUT';

    public const CATEGORIES_ALL = 'CATEGORIES_ALL';
    public const CATEGORIES_PUT = 'CATEGORIES_PUT';
    public const CATEGORIES_PATCH = 'CATEGORIES_PATCH';
    public const CATEGORIES_GET = 'CATEGORIES_GET';
    public const CATEGORIES_DELETE = 'CATEGORIES_DELETE';

    public const CLIENTS_ALL = 'CLIENTS_ALL';
    public const CLIENTS_PUT = 'CLIENTS_PUT';
    public const CLIENTS_PATCH = 'CLIENTS_PATCH';
    public const CLIENTS_GET = 'CLIENTS_GET';
    public const CLIENTS_DELETE = 'CLIENTS_DELETE';

    public const COUNTRIES_ALL = 'COUNTRIES_ALL';
    public const COUNTRIES_PUT = 'COUNTRIES_PUT';
    public const COUNTRIES_PATCH = 'COUNTRIES_PATCH';
    public const COUNTRIES_GET = 'COUNTRIES_GET';
    public const COUNTRIES_DELETE = 'COUNTRIES_DELETE';

    public const DELIVERIES_ALL = 'DELIVERIES_ALL';
    public const DELIVERIES_PUT = 'DELIVERIES_PUT';
    public const DELIVERIES_PATCH = 'DELIVERIES_PATCH';
    public const DELIVERIES_GET = 'DELIVERIES_GET';
    public const DELIVERIES_DELETE = 'DELIVERIES_DELETE';

    public const DELIVERY_METHODS_ALL = 'DELIVERY_METHODS_ALL';
    public const DELIVERY_METHODS_PUT = 'DELIVERY_METHODS_PUT';
    public const DELIVERY_METHODS_PATCH = 'DELIVERY_METHODS_PATCH';
    public const DELIVERY_METHODS_GET = 'DELIVERY_METHODS_GET';
    public const DELIVERY_METHODS_DELETE = 'DELIVERY_METHODS_DELETE';

    public const DOCUMENTS_ALL = 'DOCUMENTS_ALL';
    public const DOCUMENTS_PUT = 'DOCUMENTS_PUT';
    public const DOCUMENTS_PATCH = 'DOCUMENTS_PATCH';
    public const DOCUMENTS_GET = 'DOCUMENTS_GET';
    public const DOCUMENTS_DELETE = 'DOCUMENTS_DELETE';

    public const INVENTORIES_ALL = 'INVENTORIES_ALL';
    public const INVENTORIES_PUT = 'INVENTORIES_PUT';
    public const INVENTORIES_GET = 'INVENTORIES_GET';
    public const INVENTORIES_DELETE = 'INVENTORIES_DELETE';

    public const ORDERS_ALL = 'ORDERS_ALL';
    public const ORDERS_PUT = 'ORDERS_PUT';
    public const ORDERS_PATCH = 'ORDERS_PATCH';
    public const ORDERS_GET = 'ORDERS_GET';
    public const ORDERS_DELETE = 'ORDERS_DELETE';

    public const ORDERS_STATUS_PUT = 'ORDERS_STATUS_PUT';

    public const ORDER_ATTACHMENTS_ALL = 'ORDER_ATTACHMENTS_ALL';
    public const ORDER_ATTACHMENTS_PUT = 'ORDER_ATTACHMENTS_PUT';
    public const ORDER_ATTACHMENTS_PATCH = 'ORDER_ATTACHMENTS_PATCH';
    public const ORDER_ATTACHMENTS_GET = 'ORDER_ATTACHMENTS_GET';
    public const ORDER_ATTACHMENTS_DELETE = 'ORDER_ATTACHMENTS_DELETE';

    public const PAYMENT_METHODS_ALL = 'PAYMENT_METHODS_ALL';
    public const PAYMENT_METHODS_PUT = 'PAYMENT_METHODS_PUT';
    public const PAYMENT_METHODS_PATCH = 'PAYMENT_METHODS_PATCH';
    public const PAYMENT_METHODS_GET = 'PAYMENT_METHODS_GET';
    public const PAYMENT_METHODS_DELETE = 'PAYMENT_METHODS_DELETE';

    public const PRICE_GROUPS_ALL = 'PRICE_GROUPS_ALL';
    public const PRICE_GROUPS_PUT = 'PRICE_GROUPS_PUT';
    public const PRICE_GROUPS_GET = 'PRICE_GROUPS_GET';
    public const PRICE_GROUPS_DELETE = 'PRICE_GROUPS_DELETE';

    public const PRICE_LISTS_ALL = 'PRICE_LISTS_ALL';
    public const PRICE_LISTS_PUT = 'PRICE_LISTS_PUT';
    public const PRICE_LISTS_PATCH = 'PRICE_LISTS_PATCH';
    public const PRICE_LISTS_GET = 'PRICE_LISTS_GET';
    public const PRICE_LISTS_DELETE = 'PRICE_LISTS_DELETE';

    public const PRODUCTS_ALL = 'PRODUCTS_ALL';
    public const PRODUCTS_PUT = 'PRODUCTS_PUT';
    public const PRODUCTS_PATCH = 'PRODUCTS_PATCH';
    public const PRODUCTS_GET = 'PRODUCTS_GET';
    public const PRODUCTS_DELETE = 'PRODUCTS_DELETE';

    public const ATTRIBUTES_ALL = 'ATTRIBUTES_ALL';
    public const ATTRIBUTES_PUT = 'ATTRIBUTES_PUT';
    public const ATTRIBUTES_PATCH = 'ATTRIBUTES_PATCH';
    public const ATTRIBUTES_GET = 'ATTRIBUTES_GET';
    public const ATTRIBUTES_DELETE = 'ATTRIBUTES_DELETE';

    public const PRODUCTS_ATTRIBUTES_ALL = 'PRODUCTS_ATTRIBUTES_ALL';
    public const PRODUCTS_ATTRIBUTES_PUT = 'PRODUCTS_ATTRIBUTES_PUT';
    public const PRODUCTS_ATTRIBUTES_PATCH = 'PRODUCTS_ATTRIBUTES_PATCH';
    public const PRODUCTS_ATTRIBUTES_GET = 'PRODUCTS_ATTRIBUTES_GET';
    public const PRODUCTS_ATTRIBUTES_DELETE = 'PRODUCTS_ATTRIBUTES_DELETE';

    public const PRODUCTS_ATTACHMENTS_ALL = 'PRODUCTS_ATTACHMENTS_ALL';
    public const PRODUCTS_ATTACHMENTS_PUT = 'PRODUCTS_ATTACHMENTS_PUT';
    public const PRODUCTS_ATTACHMENTS_PATCH = 'PRODUCTS_ATTACHMENTS_PATCH';
    public const PRODUCTS_ATTACHMENTS_GET = 'PRODUCTS_ATTACHMENTS_GET';
    public const PRODUCTS_ATTACHMENTS_DELETE = 'PRODUCTS_ATTACHMENTS_DELETE';

    public const PRODUCTS_IMAGES_ALL = 'PRODUCTS_IMAGES_ALL';
    public const PRODUCTS_IMAGES_PUT = 'PRODUCTS_IMAGES_PUT';
    public const PRODUCTS_IMAGES_PATCH = 'PRODUCTS_IMAGES_PATCH';
    public const PRODUCTS_IMAGES_GET = 'PRODUCTS_IMAGES_GET';
    public const PRODUCTS_IMAGES_DELETE = 'PRODUCTS_IMAGES_DELETE';

    public const PRODUCTS_PRICES_ALL = 'PRODUCTS_PRICES_ALL';
    public const PRODUCTS_PRICES_PUT = 'PRODUCTS_PRICES_PUT';
    public const PRODUCTS_PRICES_PATCH = 'PRODUCTS_PRICES_PATCH';
    public const PRODUCTS_PRICES_GET = 'PRODUCTS_PRICES_GET';
    public const PRODUCTS_PRICES_DELETE = 'PRODUCTS_PRICES_DELETE';

    public const PRODUCTS_CATEGORIES_ALL = 'PRODUCTS_CATEGORIES_ALL';
    public const PRODUCTS_CATEGORIES_PUT = 'PRODUCTS_CATEGORIES_PUT';
    public const PRODUCTS_CATEGORIES_PATCH = 'PRODUCTS_CATEGORIES_PATCH';
    public const PRODUCTS_CATEGORIES_GET = 'PRODUCTS_CATEGORIES_GET';
    public const PRODUCTS_CATEGORIES_DELETE = 'PRODUCTS_CATEGORIES_DELETE';

    public const PRODUCTS_RELATIONS_ALL = 'PRODUCTS_RELATIONS_ALL';
    public const PRODUCTS_RELATIONS_PUT = 'PRODUCTS_RELATIONS_PUT';
    public const PRODUCTS_RELATIONS_PATCH = 'PRODUCTS_RELATIONS_PATCH';
    public const PRODUCTS_RELATIONS_GET = 'PRODUCTS_RELATIONS_GET';
    public const PRODUCTS_RELATIONS_DELETE = 'PRODUCTS_RELATIONS_DELETE';

    public const PRODUCTS_STOCKS_ALL = 'PRODUCTS_STOCKS_ALL';
    public const PRODUCTS_STOCKS_PUT = 'PRODUCTS_STOCKS_PUT';
    public const PRODUCTS_STOCKS_PATCH = 'PRODUCTS_STOCKS_PATCH';
    public const PRODUCTS_STOCKS_GET = 'PRODUCTS_STOCKS_GET';
    public const PRODUCTS_STOCKS_DELETE = 'PRODUCTS_STOCKS_DELETE';

    public const PROMOTIONS_ALL = 'PROMOTIONS_ALL';
    public const PROMOTIONS_PUT = 'PROMOTIONS_PUT';
    public const PROMOTIONS_GET = 'PROMOTIONS_GET';
    public const PROMOTIONS_DELETE = 'PROMOTIONS_DELETE';

    public const RECEIVERS_ALL = 'RECEIVERS_ALL';
    public const RECEIVERS_PUT = 'RECEIVERS_PUT';
    public const RECEIVERS_PATCH = 'RECEIVERS_PATCH';
    public const RECEIVERS_GET = 'RECEIVERS_GET';
    public const RECEIVERS_DELETE = 'RECEIVERS_DELETE';

    public const STOCKS_ALL = 'STOCKS_ALL';
    public const STOCKS_PUT = 'STOCKS_PUT';
    public const STOCKS_GET = 'STOCKS_GET';
    public const STOCKS_DELETE = 'STOCKS_DELETE';

    public const UNITS_ALL = 'UNITS_ALL';
    public const UNITS_PUT = 'UNITS_PUT';
    public const UNITS_PATCH = 'UNITS_PATCH';
    public const UNITS_GET = 'UNITS_GET';
    public const UNITS_DELETE = 'UNITS_DELETE';

    public const PRODUCTS_UNITS_ALL = 'PRODUCTS_UNITS_ALL';
    public const PRODUCTS_UNITS_PUT = 'PRODUCTS_UNITS_PUT';
    public const PRODUCTS_UNITS_PATCH = 'PRODUCTS_UNITS_PATCH';
    public const PRODUCTS_UNITS_GET = 'PRODUCTS_UNITS_GET';
    public const PRODUCTS_UNITS_DELETE = 'PRODUCTS_UNITS_DELETE';

    public const USERS_ALL = 'USERS_ALL';
    public const USERS_PUT = 'USERS_PUT';
    public const USERS_PATCH = 'USERS_PATCH';
    public const USERS_GET = 'USERS_GET';
    public const USERS_DELETE = 'USERS_DELETE';

    public const WAREHOUSES_ALL = 'WAREHOUSES_ALL';
    public const WAREHOUSES_PUT = 'WAREHOUSES_PUT';
    public const WAREHOUSES_PATCH = 'WAREHOUSES_PATCH';
    public const WAREHOUSES_GET = 'WAREHOUSES_GET';
    public const WAREHOUSES_DELETE = 'WAREHOUSES_DELETE';

    public const SETTLEMENTS_ALL = 'SETTLEMENTS_ALL';
    public const SETTLEMENTS_PUT = 'SETTLEMENTS_PUT';
    public const SETTLEMENTS_PATCH = 'SETTLEMENTS_PATCH';
    public const SETTLEMENTS_GET = 'SETTLEMENTS_GET';
    public const SETTLEMENTS_DELETE = 'SETTLEMENTS_DELETE';

    public const CURRENCY_EXCHANGE_ALL = 'CURRENCY_EXCHANGE_ALL';
    public const CURRENCY_EXCHANGE_PUT = 'CURRENCY_EXCHANGE_PUT';
    public const CURRENCY_EXCHANGE_PATCH = 'CURRENCY_EXCHANGE_PATCH';
    public const CURRENCY_EXCHANGE_GET = 'CURRENCY_EXCHANGE_GET';
    public const CURRENCY_EXCHANGE_DELETE = 'CURRENCY_EXCHANGE_DELETE';

    public const DELIVERY_PAYMENT_COST_ALL = 'DELIVERY_PAYMENT_COST_ALL';
    public const DELIVERY_PAYMENT_COST_PUT = 'DELIVERY_PAYMENT_COST_PUT';
    public const DELIVERY_PAYMENT_COST_PATCH = 'DELIVERY_PAYMENT_COST_PATCH';
    public const DELIVERY_PAYMENT_COST_GET = 'DELIVERY_PAYMENT_COST_GET';
    public const DELIVERY_PAYMENT_COST_DELETE = 'DELIVERY_PAYMENT_COST_DELETE';

    public const SERVICES_ALL = 'SERVICES_ALL';
    public const SERVICES_PUT = 'SERVICES_PUT';
    public const SERVICES_PATCH = 'SERVICES_PATCH';
    public const SERVICES_GET = 'SERVICES_GET';
    public const SERVICES_DELETE = 'SERVICES_DELETE';

    public const TRADERS_ALL = 'TRADERS_ALL';
    public const TRADERS_PUT = 'TRADERS_PUT';
    public const TRADERS_PATCH = 'TRADERS_PATCH';
    public const TRADERS_GET = 'TRADERS_GET';
    public const TRADERS_DELETE = 'TRADERS_DELETE';

    public const SECTIONS_ALL = 'SECTIONS_ALL';
    public const SECTIONS_PUT = 'SECTIONS_PUT';
    public const SECTIONS_PATCH = 'SECTIONS_PATCH';
    public const SECTIONS_GET = 'SECTIONS_GET';
    public const SECTIONS_DELETE = 'SECTIONS_DELETE';

    public const ARTICLES_ALL = 'ARTICLES_ALL';
    public const ARTICLES_PUT = 'ARTICLES_PUT';
    public const ARTICLES_PATCH = 'ARTICLES_PATCH';
    public const ARTICLES_GET = 'ARTICLES_GET';
    public const ARTICLES_DELETE = 'ARTICLES_DELETE';
}
